site_name: AgenaScript Dokumentation (Deutsch)
docs_dir: sources
theme: readthedocs
site_favicon: favicon.ico
extra_css: [custom.css]
use_directory_urls: true
repo_url: https://github.com/AgenaTrader/AgenaScript-documentation-de
edit_uri: edit/master/sources/
site_url: https://agenatrader.github.io/AgenaScript-documentation-de/index.html
strict: true
google_analytics: ['UA-74646070-1', 'agenatrader.github.io']
pages:
    - 'Los gehts': 'index.md'
    - 'Umgang mit Bars und Instrumenten': 'umgang_mit_bars_und_instrumenten.md'
    - 'Ereignisse': 'ereignisse.md'
    - 'Strategieprogrammierung': 'strategieprogrammierung.md'
    - 'Schlüsselworte': 'schluesselworte.md'
    - 'Zeichenobjekte': 'zeichenobjekte.md'
    - 'Tipps und Tricks': 'tipps_und_tricks.md'
